import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'appShop': 'Shop',
          'appAdd': 'Add',
          'appLogin': 'Login',
          'appCode': 'Code',
          'appProduct': 'Product',
          'appAddManagement': 'Add Management',
          'appBasket': 'Basket',
          'btnPhone': 'Send Code',
          'btnCode': 'Login',
          'btnBack': 'Back',
          'textFildPhone': 'Phone',
          'textFildCode': 'Code',
          'listProducts': 'Products',
          'drawerLocal': 'Languegs',
          'drawerSeting': 'Seting',
          'drawerLThemes': 'Themes',
          'Description': 'Description',
          'less': 'Show less',
          'more': 'Show more',
          'basketPrice': 'Price  ',
          'accuntPhone': 'Phone',
          'addImageFromCamera': 'Camera',
          'addImageFromgallery': 'Gallery',
          'addProduct': 'Add Product',
          'date': 'Login Date',
          'drawerlight': 'Light',
          'drawerDark': 'Dark',
          'en': 'English',
          'fa': 'Farsi',
          'exit': 'Exit'
        },
        'fa_IR': {
          'appShop': 'فروشگاه',
          'appAdd': 'افزودن',
          'appLogin': 'ورود',
          'appCode': 'کد ارسال شده',
          'appProduct': 'محصولات',
          'appAddManagement': 'مدیریت محصولات',
          'appBasket': 'سبد خرید',
          'btnPhone': 'ارسال کد',
          'btnCode': 'ورود',
          'btnBack': 'برگشت',
          'textFildPhone': 'شماره تلفن',
          'textFildCode': 'کد ارسال شده',
          'listProducts': 'محصولات',
          'drawerLocal': 'زبان',
          'drawerSeting': 'تنظیمات',
          'drawerLThemes': 'تم',
          'Description': 'توضیحات',
          'less': 'پنهان',
          'more': 'بیشتر',
          'basketPrice': ' تومان',
          'accuntPhone': 'تلفن',
          'addImageFromCamera': 'دوربین',
          'addImageFromgallery': 'گالری',
          'addProduct': 'سبد خرید خالی است',
          'date': 'زمان ورود',
          'drawerlight': 'روشن',
          'drawerDark': 'تاریک',
          'en': 'انگلیسی',
          'fa': 'فارسی',
          'exit': 'خروج'
        }
      };
}
